source 'https://rubygems.org'

gem 'activerecord'
gem 'faker'
gem 'geocoder'
gem 'httparty'
gem 'json'
gem 'pg'
gem 'rake'
gem 'rubocop', group: 'development'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'rspec'