source 'https://rubygems.org'

gem 'activerecord'
gem 'faker'
gem 'geocoder'
gem 'httparty'
gem 'json'
gem 'pg'
gem 'rake'
gem 'rspec'
gem 'rspec-sinatra'
gem 'rubocop', group: 'development'
gem 'shoulda-matchers'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'rack-test'
